//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSS.OMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string Image { get; set; }
        public string FirmName { get; set; }
        public string Address { get; set; }
        public short CustomerType { get; set; }
        public short Category { get; set; }
        public short Level { get; set; }
        public short CustomerStatus { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string LastUpdateBy { get; set; }
        public bool IsDelete { get; set; }
    }
}
