//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSS.OMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public short OperateType { get; set; }
        public string IPAddress { get; set; }
        public string IPAddressName { get; set; }
        public Nullable<int> MenuID { get; set; }
        public string MenuName { get; set; }
        public string Result { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateBy { get; set; }
    }
}
